// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/account-sync" | "/adl-monitor" | "/alpha" | "/alpha/[id]" | "/api-keys" | "/audit" | "/basis" | "/dashboard" | "/debug" | "/debug/exchange-compare" | "/execution" | "/execution-queue" | "/factors" | "/heatmap" | "/history/[symbol]" | "/local-feedback" | "/local-test-guide" | "/notifications" | "/notifications-center" | "/opportunities" | "/paper-portfolio" | "/production-console" | "/research" | "/risk-center" | "/risk-rules" | "/safety" | "/sandbox-lifecycle" | "/simulation" | "/spread-opportunities" | "/strategies" | "/testnet-readiness" | "/v121/dashboard" | "/v121/execution" | "/v121/opportunities" | "/v121/positions" | "/v121/review" | "/v121/risk-center" | "/v121/settings" | "/v121/shadow"
type AppRouteHandlerRoutes = "/api/adl-monitor" | "/api/adl-monitor/mock-refresh" | "/api/adl-settings" | "/api/basis/opportunities" | "/api/debug/exchange-compare" | "/api/debug/markets" | "/api/funding/cross-exchange" | "/api/funding/spot-perp" | "/api/history/funding" | "/api/history/opportunities" | "/api/notifications" | "/api/notifications/evaluate" | "/api/opportunities" | "/api/research/alpha" | "/api/research/alpha/[id]" | "/api/research/factors" | "/api/research/heatmap" | "/api/research/opportunities" | "/api/risk-rules" | "/api/risk-rules/[id]" | "/api/simulation/account" | "/api/simulation/history" | "/api/simulation/run" | "/api/strategies" | "/api/strategies/[id]" | "/api/strategies/[id]/clone" | "/api/summary" | "/api/testnet/account/snapshot" | "/api/testnet/orders/[id]" | "/api/testnet/orders/cancel" | "/api/testnet/orders/preview-submit" | "/api/v121/executions/paper" | "/api/v121/executions/paper/[id]" | "/api/v121/health" | "/api/v121/opportunities" | "/api/v121/opportunities/scan" | "/api/v121/positions" | "/api/v121/review" | "/api/v121/risk" | "/api/v121/risk/kill-switch" | "/api/v121/settings" | "/api/v121/shadow" | "/api/v121/shadow/account" | "/api/v121/shadow/balances" | "/api/v121/shadow/orders" | "/api/v121/shadow/positions" | "/api/v121/shadow/report" | "/api/v121/worker"
type PageRoutes = never
type LayoutRoutes = "/" | "/v121"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/account-sync": {}
  "/adl-monitor": {}
  "/alpha": {}
  "/alpha/[id]": { "id": string; }
  "/api-keys": {}
  "/api/adl-monitor": {}
  "/api/adl-monitor/mock-refresh": {}
  "/api/adl-settings": {}
  "/api/basis/opportunities": {}
  "/api/debug/exchange-compare": {}
  "/api/debug/markets": {}
  "/api/funding/cross-exchange": {}
  "/api/funding/spot-perp": {}
  "/api/history/funding": {}
  "/api/history/opportunities": {}
  "/api/notifications": {}
  "/api/notifications/evaluate": {}
  "/api/opportunities": {}
  "/api/research/alpha": {}
  "/api/research/alpha/[id]": { "id": string; }
  "/api/research/factors": {}
  "/api/research/heatmap": {}
  "/api/research/opportunities": {}
  "/api/risk-rules": {}
  "/api/risk-rules/[id]": { "id": string; }
  "/api/simulation/account": {}
  "/api/simulation/history": {}
  "/api/simulation/run": {}
  "/api/strategies": {}
  "/api/strategies/[id]": { "id": string; }
  "/api/strategies/[id]/clone": { "id": string; }
  "/api/summary": {}
  "/api/testnet/account/snapshot": {}
  "/api/testnet/orders/[id]": { "id": string; }
  "/api/testnet/orders/cancel": {}
  "/api/testnet/orders/preview-submit": {}
  "/api/v121/executions/paper": {}
  "/api/v121/executions/paper/[id]": { "id": string; }
  "/api/v121/health": {}
  "/api/v121/opportunities": {}
  "/api/v121/opportunities/scan": {}
  "/api/v121/positions": {}
  "/api/v121/review": {}
  "/api/v121/risk": {}
  "/api/v121/risk/kill-switch": {}
  "/api/v121/settings": {}
  "/api/v121/shadow": {}
  "/api/v121/shadow/account": {}
  "/api/v121/shadow/balances": {}
  "/api/v121/shadow/orders": {}
  "/api/v121/shadow/positions": {}
  "/api/v121/shadow/report": {}
  "/api/v121/worker": {}
  "/audit": {}
  "/basis": {}
  "/dashboard": {}
  "/debug": {}
  "/debug/exchange-compare": {}
  "/execution": {}
  "/execution-queue": {}
  "/factors": {}
  "/heatmap": {}
  "/history/[symbol]": { "symbol": string; }
  "/local-feedback": {}
  "/local-test-guide": {}
  "/notifications": {}
  "/notifications-center": {}
  "/opportunities": {}
  "/paper-portfolio": {}
  "/production-console": {}
  "/research": {}
  "/risk-center": {}
  "/risk-rules": {}
  "/safety": {}
  "/sandbox-lifecycle": {}
  "/simulation": {}
  "/spread-opportunities": {}
  "/strategies": {}
  "/testnet-readiness": {}
  "/v121": {}
  "/v121/dashboard": {}
  "/v121/execution": {}
  "/v121/opportunities": {}
  "/v121/positions": {}
  "/v121/review": {}
  "/v121/risk-center": {}
  "/v121/settings": {}
  "/v121/shadow": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/v121": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
