// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/account-sync/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account-sync">> = Specific
  const handler = {} as typeof import("../../app/account-sync/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/adl-monitor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/adl-monitor">> = Specific
  const handler = {} as typeof import("../../app/adl-monitor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/alpha/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/alpha/[id]">> = Specific
  const handler = {} as typeof import("../../app/alpha/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/alpha/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/alpha">> = Specific
  const handler = {} as typeof import("../../app/alpha/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api-keys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/api-keys">> = Specific
  const handler = {} as typeof import("../../app/api-keys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit">> = Specific
  const handler = {} as typeof import("../../app/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/basis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/basis">> = Specific
  const handler = {} as typeof import("../../app/basis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/debug/exchange-compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/debug/exchange-compare">> = Specific
  const handler = {} as typeof import("../../app/debug/exchange-compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/debug/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/debug">> = Specific
  const handler = {} as typeof import("../../app/debug/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/execution-queue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/execution-queue">> = Specific
  const handler = {} as typeof import("../../app/execution-queue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/execution/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/execution">> = Specific
  const handler = {} as typeof import("../../app/execution/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/factors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/factors">> = Specific
  const handler = {} as typeof import("../../app/factors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/heatmap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/heatmap">> = Specific
  const handler = {} as typeof import("../../app/heatmap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/history/[symbol]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/history/[symbol]">> = Specific
  const handler = {} as typeof import("../../app/history/[symbol]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/local-feedback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-feedback">> = Specific
  const handler = {} as typeof import("../../app/local-feedback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/local-test-guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-test-guide">> = Specific
  const handler = {} as typeof import("../../app/local-test-guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/notifications-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications-center">> = Specific
  const handler = {} as typeof import("../../app/notifications-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../app/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/opportunities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/opportunities">> = Specific
  const handler = {} as typeof import("../../app/opportunities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/paper-portfolio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/paper-portfolio">> = Specific
  const handler = {} as typeof import("../../app/paper-portfolio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/production-console/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/production-console">> = Specific
  const handler = {} as typeof import("../../app/production-console/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/research/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/research">> = Specific
  const handler = {} as typeof import("../../app/research/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/risk-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/risk-center">> = Specific
  const handler = {} as typeof import("../../app/risk-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/risk-rules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/risk-rules">> = Specific
  const handler = {} as typeof import("../../app/risk-rules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/safety/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/safety">> = Specific
  const handler = {} as typeof import("../../app/safety/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sandbox-lifecycle/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sandbox-lifecycle">> = Specific
  const handler = {} as typeof import("../../app/sandbox-lifecycle/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/simulation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/simulation">> = Specific
  const handler = {} as typeof import("../../app/simulation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/spread-opportunities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/spread-opportunities">> = Specific
  const handler = {} as typeof import("../../app/spread-opportunities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/strategies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/strategies">> = Specific
  const handler = {} as typeof import("../../app/strategies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/testnet-readiness/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/testnet-readiness">> = Specific
  const handler = {} as typeof import("../../app/testnet-readiness/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/v121/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/v121/dashboard">> = Specific
  const handler = {} as typeof import("../../app/v121/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/v121/execution/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/v121/execution">> = Specific
  const handler = {} as typeof import("../../app/v121/execution/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/v121/opportunities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/v121/opportunities">> = Specific
  const handler = {} as typeof import("../../app/v121/opportunities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/v121/positions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/v121/positions">> = Specific
  const handler = {} as typeof import("../../app/v121/positions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/v121/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/v121/review">> = Specific
  const handler = {} as typeof import("../../app/v121/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/v121/risk-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/v121/risk-center">> = Specific
  const handler = {} as typeof import("../../app/v121/risk-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/v121/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/v121/settings">> = Specific
  const handler = {} as typeof import("../../app/v121/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/v121/shadow/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/v121/shadow">> = Specific
  const handler = {} as typeof import("../../app/v121/shadow/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/adl-monitor/mock-refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/adl-monitor/mock-refresh">> = Specific
  const handler = {} as typeof import("../../app/api/adl-monitor/mock-refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/adl-monitor/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/adl-monitor">> = Specific
  const handler = {} as typeof import("../../app/api/adl-monitor/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/adl-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/adl-settings">> = Specific
  const handler = {} as typeof import("../../app/api/adl-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/basis/opportunities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/basis/opportunities">> = Specific
  const handler = {} as typeof import("../../app/api/basis/opportunities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/debug/exchange-compare/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/exchange-compare">> = Specific
  const handler = {} as typeof import("../../app/api/debug/exchange-compare/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/debug/markets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/markets">> = Specific
  const handler = {} as typeof import("../../app/api/debug/markets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/funding/cross-exchange/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/funding/cross-exchange">> = Specific
  const handler = {} as typeof import("../../app/api/funding/cross-exchange/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/funding/spot-perp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/funding/spot-perp">> = Specific
  const handler = {} as typeof import("../../app/api/funding/spot-perp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/history/funding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/history/funding">> = Specific
  const handler = {} as typeof import("../../app/api/history/funding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/history/opportunities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/history/opportunities">> = Specific
  const handler = {} as typeof import("../../app/api/history/opportunities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/notifications/evaluate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/evaluate">> = Specific
  const handler = {} as typeof import("../../app/api/notifications/evaluate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/opportunities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/opportunities">> = Specific
  const handler = {} as typeof import("../../app/api/opportunities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/research/alpha/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/research/alpha/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/research/alpha/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/research/alpha/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/research/alpha">> = Specific
  const handler = {} as typeof import("../../app/api/research/alpha/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/research/factors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/research/factors">> = Specific
  const handler = {} as typeof import("../../app/api/research/factors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/research/heatmap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/research/heatmap">> = Specific
  const handler = {} as typeof import("../../app/api/research/heatmap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/research/opportunities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/research/opportunities">> = Specific
  const handler = {} as typeof import("../../app/api/research/opportunities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/risk-rules/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/risk-rules/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/risk-rules/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/risk-rules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/risk-rules">> = Specific
  const handler = {} as typeof import("../../app/api/risk-rules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/simulation/account/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/simulation/account">> = Specific
  const handler = {} as typeof import("../../app/api/simulation/account/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/simulation/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/simulation/history">> = Specific
  const handler = {} as typeof import("../../app/api/simulation/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/simulation/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/simulation/run">> = Specific
  const handler = {} as typeof import("../../app/api/simulation/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/strategies/[id]/clone/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/strategies/[id]/clone">> = Specific
  const handler = {} as typeof import("../../app/api/strategies/[id]/clone/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/strategies/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/strategies/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/strategies/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/strategies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/strategies">> = Specific
  const handler = {} as typeof import("../../app/api/strategies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/summary">> = Specific
  const handler = {} as typeof import("../../app/api/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/testnet/account/snapshot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/testnet/account/snapshot">> = Specific
  const handler = {} as typeof import("../../app/api/testnet/account/snapshot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/testnet/orders/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/testnet/orders/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/testnet/orders/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/testnet/orders/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/testnet/orders/cancel">> = Specific
  const handler = {} as typeof import("../../app/api/testnet/orders/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/testnet/orders/preview-submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/testnet/orders/preview-submit">> = Specific
  const handler = {} as typeof import("../../app/api/testnet/orders/preview-submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v121/executions/paper/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v121/executions/paper/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/v121/executions/paper/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v121/executions/paper/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v121/executions/paper">> = Specific
  const handler = {} as typeof import("../../app/api/v121/executions/paper/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v121/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v121/health">> = Specific
  const handler = {} as typeof import("../../app/api/v121/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v121/opportunities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v121/opportunities">> = Specific
  const handler = {} as typeof import("../../app/api/v121/opportunities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v121/opportunities/scan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v121/opportunities/scan">> = Specific
  const handler = {} as typeof import("../../app/api/v121/opportunities/scan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v121/positions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v121/positions">> = Specific
  const handler = {} as typeof import("../../app/api/v121/positions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v121/review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v121/review">> = Specific
  const handler = {} as typeof import("../../app/api/v121/review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v121/risk/kill-switch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v121/risk/kill-switch">> = Specific
  const handler = {} as typeof import("../../app/api/v121/risk/kill-switch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v121/risk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v121/risk">> = Specific
  const handler = {} as typeof import("../../app/api/v121/risk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v121/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v121/settings">> = Specific
  const handler = {} as typeof import("../../app/api/v121/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v121/shadow/account/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v121/shadow/account">> = Specific
  const handler = {} as typeof import("../../app/api/v121/shadow/account/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v121/shadow/balances/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v121/shadow/balances">> = Specific
  const handler = {} as typeof import("../../app/api/v121/shadow/balances/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v121/shadow/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v121/shadow/orders">> = Specific
  const handler = {} as typeof import("../../app/api/v121/shadow/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v121/shadow/positions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v121/shadow/positions">> = Specific
  const handler = {} as typeof import("../../app/api/v121/shadow/positions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v121/shadow/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v121/shadow/report">> = Specific
  const handler = {} as typeof import("../../app/api/v121/shadow/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v121/shadow/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v121/shadow">> = Specific
  const handler = {} as typeof import("../../app/api/v121/shadow/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v121/worker/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v121/worker">> = Specific
  const handler = {} as typeof import("../../app/api/v121/worker/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/v121/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/v121">> = Specific
  const handler = {} as typeof import("../../app/v121/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
